version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: flight_booking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: FlightBookingDb
    ports:
      - "5432:5432"
    volumes:
      - flight_db_data:/var/lib/postgresql/data

volumes:
  flight_db_data: